// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAccessibilityPermission() {
  return window['go']['main']['App']['CheckAccessibilityPermission']();
}

export function CheckMicrophonePermission() {
  return window['go']['main']['App']['CheckMicrophonePermission']();
}

export function ClearLoginToken() {
  return window['go']['main']['App']['ClearLoginToken']();
}

export function CreateBoard(arg1) {
  return window['go']['main']['App']['CreateBoard'](arg1);
}

export function CreateCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCard'](arg1, arg2, arg3);
}

export function CreateCollaborationRoom() {
  return window['go']['main']['App']['CreateCollaborationRoom']();
}

export function CreateColumn(arg1, arg2) {
  return window['go']['main']['App']['CreateColumn'](arg1, arg2);
}

export function DeleteBoard(arg1) {
  return window['go']['main']['App']['DeleteBoard'](arg1);
}

export function DeleteCard(arg1) {
  return window['go']['main']['App']['DeleteCard'](arg1);
}

export function DeleteColumn(arg1) {
  return window['go']['main']['App']['DeleteColumn'](arg1);
}

export function GetBoardByID(arg1) {
  return window['go']['main']['App']['GetBoardByID'](arg1);
}

export function GetBoards(arg1, arg2) {
  return window['go']['main']['App']['GetBoards'](arg1, arg2);
}

export function GetCard(arg1) {
  return window['go']['main']['App']['GetCard'](arg1);
}

export function GetCloudAPIURL() {
  return window['go']['main']['App']['GetCloudAPIURL']();
}

export function GetCollabServerAddress() {
  return window['go']['main']['App']['GetCollabServerAddress']();
}

export function GetCollaborationRoomId() {
  return window['go']['main']['App']['GetCollaborationRoomId']();
}

export function GetColumn(arg1) {
  return window['go']['main']['App']['GetColumn'](arg1);
}

export function GetCurrentBoardId() {
  return window['go']['main']['App']['GetCurrentBoardId']();
}

export function GetLoginToken() {
  return window['go']['main']['App']['GetLoginToken']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTranscriptionByID(arg1) {
  return window['go']['main']['App']['GetTranscriptionByID'](arg1);
}

export function GetTranscriptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTranscriptions'](arg1, arg2, arg3);
}

export function GetWebURL() {
  return window['go']['main']['App']['GetWebURL']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportNewBoard(arg1) {
  return window['go']['main']['App']['ImportNewBoard'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function JoinCollaborationRoom(arg1) {
  return window['go']['main']['App']['JoinCollaborationRoom'](arg1);
}

export function LeaveCollaborationRoom(arg1) {
  return window['go']['main']['App']['LeaveCollaborationRoom'](arg1);
}

export function ListCardsByColumn(arg1) {
  return window['go']['main']['App']['ListCardsByColumn'](arg1);
}

export function ListColumnsByBoard(arg1) {
  return window['go']['main']['App']['ListColumnsByBoard'](arg1);
}

export function OpenAccessibilitySettings() {
  return window['go']['main']['App']['OpenAccessibilitySettings']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenMicrophoneSettings() {
  return window['go']['main']['App']['OpenMicrophoneSettings']();
}

export function ReadAudioFile(arg1) {
  return window['go']['main']['App']['ReadAudioFile'](arg1);
}

export function ReprocessTranscription(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReprocessTranscription'](arg1, arg2, arg3);
}

export function RequestAccessibilityPermission() {
  return window['go']['main']['App']['RequestAccessibilityPermission']();
}

export function RequestMicrophonePermission() {
  return window['go']['main']['App']['RequestMicrophonePermission']();
}

export function SaveSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4);
}

export function SetCurrentBoardId(arg1) {
  return window['go']['main']['App']['SetCurrentBoardId'](arg1);
}

export function SetLoginToken(arg1) {
  return window['go']['main']['App']['SetLoginToken'](arg1);
}

export function UpdateBoard(arg1, arg2) {
  return window['go']['main']['App']['UpdateBoard'](arg1, arg2);
}

export function UpdateCard(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCard'](arg1, arg2, arg3);
}

export function UpdateCardColumn(arg1, arg2) {
  return window['go']['main']['App']['UpdateCardColumn'](arg1, arg2);
}

export function UpdateColumn(arg1, arg2) {
  return window['go']['main']['App']['UpdateColumn'](arg1, arg2);
}
