// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {query} from '../models';
import {frontend} from '../models';

export function CheckAccessibilityPermission():Promise<number>;

export function CheckMicrophonePermission():Promise<number>;

export function ClearLoginToken():Promise<void>;

export function CreateBoard(arg1:string):Promise<query.Board>;

export function CreateCard(arg1:string,arg2:string,arg3:string):Promise<query.Card>;

export function CreateCollaborationRoom():Promise<void>;

export function CreateColumn(arg1:string,arg2:string):Promise<query.Column>;

export function DeleteBoard(arg1:string):Promise<void>;

export function DeleteCard(arg1:string):Promise<void>;

export function DeleteColumn(arg1:string):Promise<void>;

export function ExportDataForSync():Promise<Record<string, any>>;

export function GetBoardByID(arg1:string):Promise<query.Board>;

export function GetBoards(arg1:number,arg2:number):Promise<Array<query.Board>>;

export function GetCard(arg1:string):Promise<query.Card>;

export function GetCollaborationRoomId():Promise<string>;

export function GetColumn(arg1:string):Promise<query.Column>;

export function GetLoginToken():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, any>>;

export function GetSettings():Promise<query.Setting>;

export function GetTranscriptionByID(arg1:string):Promise<query.Transcription>;

export function GetTranscriptions(arg1:string,arg2:number,arg3:number):Promise<Array<query.Transcription>>;

export function Greet(arg1:string):Promise<string>;

export function ImportNewBoard(arg1:string):Promise<void>;

export function JoinCollaborationRoom(arg1:string):Promise<void>;

export function LeaveCollaborationRoom(arg1:string):Promise<string>;

export function ListCardsByColumn(arg1:string):Promise<Array<query.Card>>;

export function ListColumnsByBoard(arg1:string):Promise<Array<query.Column>>;

export function OpenAccessibilitySettings():Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function OpenMicrophoneSettings():Promise<void>;

export function RequestAccessibilityPermission():Promise<void>;

export function RequestMicrophonePermission():Promise<boolean>;

export function SaveSettings(arg1:string,arg2:any,arg3:any,arg4:any):Promise<query.Setting>;

export function SetLoginToken(arg1:string):Promise<void>;

export function StartDataSyncing(arg1:string):Promise<void>;

export function UpdateBoard(arg1:string,arg2:string):Promise<query.Board>;

export function UpdateCard(arg1:string,arg2:string,arg3:string):Promise<query.Card>;

export function UpdateCardColumn(arg1:string,arg2:string):Promise<query.Card>;

export function UpdateColumn(arg1:string,arg2:string):Promise<query.Column>;
