// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {query} from '../models';
import {frontend} from '../models';

export function CheckAccessibilityPermission():Promise<number>;

export function CheckMicrophonePermission():Promise<number>;

export function ClearLoginToken():Promise<void>;

export function CreateBoard(arg1:string):Promise<types.ExportedBoard>;

export function CreateCard(arg1:string,arg2:string,arg3:string):Promise<types.ExportedCard>;

export function CreateCollaborationRoom():Promise<void>;

export function CreateColumn(arg1:string,arg2:string):Promise<types.ExportedColumn>;

export function DeleteBoard(arg1:string):Promise<void>;

export function DeleteCard(arg1:string):Promise<void>;

export function DeleteColumn(arg1:string):Promise<void>;

export function GetBoardByID(arg1:string):Promise<types.ExportedBoard>;

export function GetBoards(arg1:number,arg2:number):Promise<Array<types.ExportedBoard>>;

export function GetCard(arg1:string):Promise<types.ExportedCard>;

export function GetCollaborationRoomId():Promise<string>;

export function GetColumn(arg1:string):Promise<types.ExportedColumn>;

export function GetCurrentBoardId():Promise<string>;

export function GetLoginToken():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, any>>;

export function GetSettings():Promise<query.Setting>;

export function GetTranscriptionByID(arg1:string):Promise<types.ExportedTranscription>;

export function GetTranscriptions(arg1:string,arg2:number,arg3:number):Promise<Array<types.ExportedTranscription>>;

export function Greet(arg1:string):Promise<string>;

export function ImportNewBoard(arg1:string):Promise<void>;

export function InstallUpdate(arg1:types.AppVersion):Promise<void>;

export function JoinCollaborationRoom(arg1:string):Promise<void>;

export function LeaveCollaborationRoom(arg1:string):Promise<string>;

export function ListCardsByColumn(arg1:string):Promise<Array<types.ExportedCard>>;

export function ListColumnsByBoard(arg1:string):Promise<Array<types.ExportedColumn>>;

export function OpenAccessibilitySettings():Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function OpenMicrophoneSettings():Promise<void>;

export function ReprocessTranscription(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RequestAccessibilityPermission():Promise<void>;

export function RequestMicrophonePermission():Promise<boolean>;

export function SaveSettings(arg1:string,arg2:any,arg3:any,arg4:any):Promise<query.Setting>;

export function SetCurrentBoardId(arg1:string):Promise<void>;

export function SetLoginToken(arg1:string):Promise<void>;

export function StartDataSyncing(arg1:string):Promise<void>;

export function UpdateBoard(arg1:string,arg2:string):Promise<types.ExportedBoard>;

export function UpdateCard(arg1:string,arg2:string,arg3:string):Promise<types.ExportedCard>;

export function UpdateCardColumn(arg1:string,arg2:string):Promise<types.ExportedCard>;

export function UpdateColumn(arg1:string,arg2:string):Promise<types.ExportedColumn>;
