// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
)

type Board struct {
	ID        string
	Name      string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Card struct {
	ID          string
	ColumnID    string
	Title       string
	Description sql.NullString
	Attachments sql.NullString
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

type Column struct {
	ID        string
	BoardID   string
	Name      string
	Position  int64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Setting struct {
	ID                  int64
	TranscriptionMethod string
	WhisperBinaryPath   sql.NullString
	WhisperModelPath    sql.NullString
	OpenaiApiKey        sql.NullString
	CreatedAt           sql.NullString
	UpdatedAt           sql.NullString
}

type Transcription struct {
	ID                string
	BoardID           string
	Transcription     string
	RecordingPath     sql.NullString
	Intent            sql.NullString
	AssistantResponse sql.NullString
	CreatedAt         sql.NullString
	UpdatedAt         sql.NullString
}
