// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package query

import (
	"context"
	"database/sql"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, name)
VALUES (?, ?)
RETURNING id, name, created_at, updated_at
`

type CreateBoardParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.ID, arg.Name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (id, board_id, title, position)
VALUES (?, ?, ?, ?)
RETURNING id, board_id, title, position, created_at, updated_at
`

type CreateColumnParams struct {
	ID       string
	BoardID  string
	Title    string
	Position int64
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.ID,
		arg.BoardID,
		arg.Title,
		arg.Position,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSettings = `-- name: CreateSettings :one
INSERT INTO settings (id, transcription_method, whisper_binary_path, whisper_model_path, openai_api_key)
VALUES (1, ?, ?, ?, ?)
RETURNING id, transcription_method, whisper_binary_path, whisper_model_path, openai_api_key, created_at, updated_at
`

type CreateSettingsParams struct {
	TranscriptionMethod string
	WhisperBinaryPath   sql.NullString
	WhisperModelPath    sql.NullString
	OpenaiApiKey        sql.NullString
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, createSettings,
		arg.TranscriptionMethod,
		arg.WhisperBinaryPath,
		arg.WhisperModelPath,
		arg.OpenaiApiKey,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TranscriptionMethod,
		&i.WhisperBinaryPath,
		&i.WhisperModelPath,
		&i.OpenaiApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, column_id, title, description, assignee_id, story_points, pr_link, ticket_type)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, column_id, title, description, assignee_id, story_points, pr_link, ticket_type, created_at, updated_at
`

type CreateTicketParams struct {
	ID          string
	ColumnID    string
	Title       string
	Description sql.NullString
	AssigneeID  sql.NullInt64
	StoryPoints sql.NullInt64
	PrLink      sql.NullString
	TicketType  string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket,
		arg.ID,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.StoryPoints,
		arg.PrLink,
		arg.TicketType,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.PrLink,
		&i.TicketType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTranscription = `-- name: CreateTranscription :one
INSERT INTO transcriptions (id, board_id, transcription, recording_path, intent, assistant_response)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at
`

type CreateTranscriptionParams struct {
	ID                string
	BoardID           string
	Transcription     string
	RecordingPath     sql.NullString
	Intent            sql.NullString
	AssistantResponse sql.NullString
}

func (q *Queries) CreateTranscription(ctx context.Context, arg CreateTranscriptionParams) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, createTranscription,
		arg.ID,
		arg.BoardID,
		arg.Transcription,
		arg.RecordingPath,
		arg.Intent,
		arg.AssistantResponse,
	)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Transcription,
		&i.RecordingPath,
		&i.Intent,
		&i.AssistantResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = ?
`

func (q *Queries) DeleteBoard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, id)
	return err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns
WHERE id = ?
`

func (q *Queries) DeleteColumn(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, id)
	return err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE id = ?
`

func (q *Queries) DeleteTicket(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

const deleteTranscription = `-- name: DeleteTranscription :exec
DELETE FROM transcriptions
WHERE id = ?
`

func (q *Queries) DeleteTranscription(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTranscription, id)
	return err
}

const getBoard = `-- name: GetBoard :one

SELECT id, name, created_at, updated_at FROM boards
WHERE id = ?
LIMIT 1
`

// Board Functionality
func (q *Queries) GetBoard(ctx context.Context, id string) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one

SELECT id, board_id, title, position, created_at, updated_at FROM columns
WHERE id = ?
LIMIT 1
`

// Columns Functionality
func (q *Queries) GetColumn(ctx context.Context, id string) (Column, error) {
	row := q.db.QueryRowContext(ctx, getColumn, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one

SELECT id, transcription_method, whisper_binary_path, whisper_model_path, openai_api_key, created_at, updated_at FROM settings
WHERE id = 1
LIMIT 1
`

// Settings Functionality
func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TranscriptionMethod,
		&i.WhisperBinaryPath,
		&i.WhisperModelPath,
		&i.OpenaiApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one

SELECT id, column_id, title, description, assignee_id, story_points, pr_link, ticket_type, created_at, updated_at FROM tickets
WHERE id = ?
LIMIT 1
`

// Tickets Functionality
func (q *Queries) GetTicket(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.PrLink,
		&i.TicketType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscription = `-- name: GetTranscription :one

SELECT id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at FROM transcriptions
WHERE id = ?
LIMIT 1
`

// Transcriptions Functionality
func (q *Queries) GetTranscription(ctx context.Context, id string) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getTranscription, id)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Transcription,
		&i.RecordingPath,
		&i.Intent,
		&i.AssistantResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscriptionByRecordingPath = `-- name: GetTranscriptionByRecordingPath :one
SELECT id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at FROM transcriptions
where recording_path = ? AND board_id = ?
`

type GetTranscriptionByRecordingPathParams struct {
	RecordingPath sql.NullString
	BoardID       string
}

func (q *Queries) GetTranscriptionByRecordingPath(ctx context.Context, arg GetTranscriptionByRecordingPathParams) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptionByRecordingPath, arg.RecordingPath, arg.BoardID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Transcription,
		&i.RecordingPath,
		&i.Intent,
		&i.AssistantResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTranscriptions = `-- name: ListAllTranscriptions :many
SELECT id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at FROM transcriptions
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAllTranscriptionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllTranscriptions(ctx context.Context, arg ListAllTranscriptionsParams) ([]Transcription, error) {
	rows, err := q.db.QueryContext(ctx, listAllTranscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcription
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Transcription,
			&i.RecordingPath,
			&i.Intent,
			&i.AssistantResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, name, created_at, updated_at FROM boards
ORDER BY created_at ASC
LIMIT ? OFFSET ?
`

type ListBoardsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListBoards(ctx context.Context, arg ListBoardsParams) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, listBoards, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumnsByBoard = `-- name: ListColumnsByBoard :many
SELECT id, board_id, title, position, created_at, updated_at FROM columns
WHERE board_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListColumnsByBoard(ctx context.Context, boardID string) ([]Column, error) {
	rows, err := q.db.QueryContext(ctx, listColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Column
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByColumn = `-- name: ListTicketsByColumn :many
SELECT id, column_id, title, description, assignee_id, story_points, pr_link, ticket_type, created_at, updated_at FROM tickets
WHERE column_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListTicketsByColumn(ctx context.Context, columnID string) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.StoryPoints,
			&i.PrLink,
			&i.TicketType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptionsByBoard = `-- name: ListTranscriptionsByBoard :many
SELECT id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at FROM transcriptions
WHERE board_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTranscriptionsByBoard(ctx context.Context, boardID string) ([]Transcription, error) {
	rows, err := q.db.QueryContext(ctx, listTranscriptionsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transcription
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Transcription,
			&i.RecordingPath,
			&i.Intent,
			&i.AssistantResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, created_at, updated_at
`

type UpdateBoardParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, updateBoard, arg.Name, arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET title = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, board_id, title, position, created_at, updated_at
`

type UpdateColumnParams struct {
	Title string
	ID    string
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, updateColumn, arg.Title, arg.ID)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET transcription_method = ?,
    whisper_binary_path = ?,
    whisper_model_path = ?,
    openai_api_key = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, transcription_method, whisper_binary_path, whisper_model_path, openai_api_key, created_at, updated_at
`

type UpdateSettingsParams struct {
	TranscriptionMethod string
	WhisperBinaryPath   sql.NullString
	WhisperModelPath    sql.NullString
	OpenaiApiKey        sql.NullString
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.TranscriptionMethod,
		arg.WhisperBinaryPath,
		arg.WhisperModelPath,
		arg.OpenaiApiKey,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.TranscriptionMethod,
		&i.WhisperBinaryPath,
		&i.WhisperModelPath,
		&i.OpenaiApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET title = ?,
    description = ?,
    assignee_id = ?,
    story_points = ?,
    pr_link = ?,
    ticket_type = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, column_id, title, description, assignee_id, story_points, pr_link, ticket_type, created_at, updated_at
`

type UpdateTicketParams struct {
	Title       string
	Description sql.NullString
	AssigneeID  sql.NullInt64
	StoryPoints sql.NullInt64
	PrLink      sql.NullString
	TicketType  string
	ID          string
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicket,
		arg.Title,
		arg.Description,
		arg.AssigneeID,
		arg.StoryPoints,
		arg.PrLink,
		arg.TicketType,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.PrLink,
		&i.TicketType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicketColumn = `-- name: UpdateTicketColumn :one
UPDATE tickets
SET column_id = ?
WHERE id = ?
RETURNING id, column_id, title, description, assignee_id, story_points, pr_link, ticket_type, created_at, updated_at
`

type UpdateTicketColumnParams struct {
	ColumnID string
	ID       string
}

func (q *Queries) UpdateTicketColumn(ctx context.Context, arg UpdateTicketColumnParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, updateTicketColumn, arg.ColumnID, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.PrLink,
		&i.TicketType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranscriptionIntent = `-- name: UpdateTranscriptionIntent :one
UPDATE transcriptions
SET intent = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at
`

type UpdateTranscriptionIntentParams struct {
	Intent sql.NullString
	ID     string
}

func (q *Queries) UpdateTranscriptionIntent(ctx context.Context, arg UpdateTranscriptionIntentParams) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, updateTranscriptionIntent, arg.Intent, arg.ID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Transcription,
		&i.RecordingPath,
		&i.Intent,
		&i.AssistantResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranscriptionResponse = `-- name: UpdateTranscriptionResponse :one
UPDATE transcriptions
SET assistant_response = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, board_id, transcription, recording_path, intent, assistant_response, created_at, updated_at
`

type UpdateTranscriptionResponseParams struct {
	AssistantResponse sql.NullString
	ID                string
}

func (q *Queries) UpdateTranscriptionResponse(ctx context.Context, arg UpdateTranscriptionResponseParams) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, updateTranscriptionResponse, arg.AssistantResponse, arg.ID)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Transcription,
		&i.RecordingPath,
		&i.Intent,
		&i.AssistantResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
