// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package centraldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DesktopLoginCode struct {
	Code      string
	UserID    pgtype.UUID
	State     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type User struct {
	ID                  pgtype.UUID
	Email               string
	PasswordHash        string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ResetToken          pgtype.Text
	ResetTokenExpiresAt pgtype.Timestamptz
}
