// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package centraldb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppVersion struct {
	ID        int32
	Version   string
	Url       string
	Notes     pgtype.Text
	Sha256    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Board struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BoardMember struct {
	BoardID  pgtype.UUID
	UserID   pgtype.UUID
	Role     pgtype.Text
	JoinedAt pgtype.Timestamptz
}

type Card struct {
	ID          string
	ColumnID    string
	Title       string
	Description pgtype.Text
	Attachments pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Column struct {
	ID        string
	BoardID   pgtype.UUID
	Name      string
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DesktopLoginCode struct {
	Code      string
	UserID    pgtype.UUID
	State     string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Notification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Message   string
	Type      string
	Target    pgtype.Text
	Read      pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type Operation struct {
	ID            string
	TableName     string
	RecordID      string
	OperationType string
	DeviceID      pgtype.Text
	Payload       string
	CreatedAt     pgtype.Text
	UpdatedAt     pgtype.Text
}

type SyncState struct {
	UserID         pgtype.UUID
	TableName      string
	LastSyncedAt   int64
	LastSyncedOpID pgtype.Text
}

type Transcription struct {
	ID                string
	BoardID           pgtype.UUID
	Transcription     string
	RecordingPath     pgtype.Text
	Intent            pgtype.Text
	AssistantResponse pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type User struct {
	ID                  pgtype.UUID
	Email               string
	PasswordHash        string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ResetToken          pgtype.Text
	ResetTokenExpiresAt pgtype.Timestamptz
	CloudInitialized    pgtype.Bool
}
