// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBoard(arg1) {
  return window['go']['main']['App']['CreateBoard'](arg1);
}

export function CreateColumn(arg1, arg2) {
  return window['go']['main']['App']['CreateColumn'](arg1, arg2);
}

export function CreateTicket(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTicket'](arg1, arg2, arg3, arg4);
}

export function DeleteBoard(arg1) {
  return window['go']['main']['App']['DeleteBoard'](arg1);
}

export function DeleteColumn(arg1) {
  return window['go']['main']['App']['DeleteColumn'](arg1);
}

export function DeleteTicket(arg1) {
  return window['go']['main']['App']['DeleteTicket'](arg1);
}

export function GetBoardByID(arg1) {
  return window['go']['main']['App']['GetBoardByID'](arg1);
}

export function GetBoards(arg1, arg2) {
  return window['go']['main']['App']['GetBoards'](arg1, arg2);
}

export function GetColumn(arg1) {
  return window['go']['main']['App']['GetColumn'](arg1);
}

export function GetTicket(arg1) {
  return window['go']['main']['App']['GetTicket'](arg1);
}

export function GetTranscriptionByID(arg1) {
  return window['go']['main']['App']['GetTranscriptionByID'](arg1);
}

export function GetTranscriptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTranscriptions'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListColumnsByBoard(arg1) {
  return window['go']['main']['App']['ListColumnsByBoard'](arg1);
}

export function ListTicketsByColumn(arg1) {
  return window['go']['main']['App']['ListTicketsByColumn'](arg1);
}

export function UpdateBoard(arg1, arg2) {
  return window['go']['main']['App']['UpdateBoard'](arg1, arg2);
}

export function UpdateColumn(arg1, arg2) {
  return window['go']['main']['App']['UpdateColumn'](arg1, arg2);
}

export function UpdateTicket(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTicket'](arg1, arg2, arg3);
}

export function UpdateTicketColumn(arg1, arg2) {
  return window['go']['main']['App']['UpdateTicketColumn'](arg1, arg2);
}
