// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {query} from '../models';

export function CreateBoard(arg1:string):Promise<query.Board>;

export function CreateColumn(arg1:string,arg2:string):Promise<query.Column>;

export function CreateTicket(arg1:string,arg2:string,arg3:string,arg4:string):Promise<query.Ticket>;

export function DeleteBoard(arg1:string):Promise<void>;

export function DeleteColumn(arg1:string):Promise<void>;

export function DeleteTicket(arg1:string):Promise<void>;

export function GetBoardByID(arg1:string):Promise<query.Board>;

export function GetBoards(arg1:number,arg2:number):Promise<Array<query.Board>>;

export function GetColumn(arg1:string):Promise<query.Column>;

export function GetTicket(arg1:string):Promise<query.Ticket>;

export function GetTranscriptionByID(arg1:string):Promise<query.Transcription>;

export function GetTranscriptions(arg1:string,arg2:number,arg3:number):Promise<Array<query.Transcription>>;

export function Greet(arg1:string):Promise<string>;

export function ListColumnsByBoard(arg1:string):Promise<Array<query.Column>>;

export function ListTicketsByColumn(arg1:string):Promise<Array<query.Ticket>>;

export function UpdateBoard(arg1:string,arg2:string):Promise<query.Board>;

export function UpdateColumn(arg1:string,arg2:string):Promise<query.Column>;

export function UpdateTicket(arg1:string,arg2:string,arg3:string):Promise<query.Ticket>;

export function UpdateTicketColumn(arg1:string,arg2:string):Promise<query.Ticket>;
