name: Wails macOS build

on:
  push:
    tags:
      - '*'   # Trigger on any new tag

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Build Universal App + DMG
        run: make installer

      - name: Archive DMG
        run: |
          mkdir -p artifacts
          cp dist/Seisami.dmg artifacts/Seisami-${GITHUB_REF_NAME}-macos.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Seisami-macos
          path: artifacts/*.dmg

  release:
    needs: build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Seisami-macos
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
